const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const fs = require('fs');
const path = require('path');

/**
 * Generates a professional match PDF document with a QR code and watermark.
 * @param {Object} match Data of the DonationMatch
 * @param {Object} seeker Seeker user data
 * @param {Object} donor Donor user data
 * @param {Object} facility Facility details (Hospital or BloodBank)
 * @returns {Promise<string>} Path to the saved PDF file
 */
const generateMatchPDF = async (match, seeker, donor, facility) => {
  return new Promise(async (resolve, reject) => {
    try {
      const pdfDir = path.join(__dirname, '../../uploads/pdfs');
      if (!fs.existsSync(pdfDir)) {
        fs.mkdirSync(pdfDir, { recursive: true });
      }

      const fileName = `match_${match.matchObid}.pdf`;
      const filePath = path.join(pdfDir, fileName);
      const doc = new PDFDocument({ margin: 50, size: 'A4' });

      const writeStream = fs.createWriteStream(filePath);
      doc.pipe(writeStream);

      // 1. Watermark Background
      doc.save();
      doc.opacity(0.04);
      doc.fontSize(80).fillColor('#B91C1C');
      // Draw diagonal watermark text
      doc.translate(300, 400).rotate(-45);
      doc.text('ONEBLOOD', -250, 0, { align: 'center', width: 500 });
      doc.restore();

      // 2. Header Section
      doc.fillColor('#B91C1C').fontSize(26).text('OneBlood', { align: 'left' });
      doc.fillColor('#4B5563').fontSize(12).text('Saving Lives Together', { align: 'left' });
      
      doc.moveDown(0.5);
      doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(1);

      // 3. Match Highlight Card
      doc.fillColor('#FEF2F2').rect(50, doc.y, 495, 60).fill();
      doc.fillColor('#991B1B').fontSize(14).text(`MATCH ID: ${match.matchObid}`, 65, doc.y + 12, { bold: true });
      doc.fillColor('#7F1D1D').fontSize(10).text(`Status: IN PROGRESS  |  Generated on: ${new Date().toLocaleString()}`, 65, doc.y + 32);
      
      doc.moveDown(3);

      // 4. Details Grid
      const startY = doc.y;
      
      // Column 1: Seeker & Donor
      doc.fillColor('#1F2937').fontSize(12).text('Requisition Details', 50, startY, { underline: true });
      doc.fontSize(10).fillColor('#4B5563');
      doc.text(`Seeker Name: ${seeker.name}`, 50, startY + 20);
      doc.text(`Contact: ${seeker.phone || 'N/A'}`, 50, startY + 35);
      doc.text(`Blood Group Required: ${match.bloodGroup}`, 50, startY + 50);
      doc.text(`Units: ${match.units}`, 50, startY + 65);

      doc.fillColor('#1F2937').fontSize(12).text('Donor Details', 50, startY + 95, { underline: true });
      doc.fontSize(10).fillColor('#4B5563');
      doc.text(`Donor Name: ${donor.name}`, 50, startY + 115);
      doc.text(`OneBlood ID: ${donor.onebloodId}`, 50, startY + 130);

      // Column 2: Facility & QR Code
      const col2X = 320;
      doc.fillColor('#1F2937').fontSize(12).text('Destination Facility', col2X, startY, { underline: true });
      doc.fontSize(10).fillColor('#4B5563');
      const facName = facility.hospitalName || facility.name || 'Selected Facility';
      const facAddr = facility.address || 'N/A';
      const facContact = facility.emergencyContact || facility.phone || 'N/A';
      
      doc.text(`Name: ${facName}`, col2X, startY + 20, { width: 220 });
      doc.text(`Address: ${facAddr}`, col2X, startY + 35, { width: 220 });
      doc.text(`Emergency Phone: ${facContact}`, col2X, startY + 65);

      // Generate and Embed QR Code
      const qrDataUrl = `${process.env.FRONTEND_URL || 'http://localhost:5173'}/match/${match.matchObid}`;
      const qrBuffer = await QRCode.toBuffer(qrDataUrl, { margin: 1, width: 90 });
      doc.image(qrBuffer, col2X, startY + 95, { width: 85 });
      doc.fontSize(8).fillColor('#9CA3AF').text('Scan to verify match status online', col2X, startY + 185);

      // 5. Footer Section
      doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, 720).lineTo(545, 720).stroke();
      doc.fillColor('#9CA3AF').fontSize(9).text('Generated by OneBlood — Connecting lives, one drop at a time.', 50, 735, { align: 'center' });

      doc.end();

      writeStream.on('finish', () => {
        resolve(filePath);
      });

      writeStream.on('error', (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateMatchPDF
};
